### ISSUE TITLE
Searches have a fair amount of lag

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#175]
Seems considerably more than it used to be a few weeks ago? @ccstan99 has anything relevant changed?

**Comment by Aprillion** [comment]
I removed the initial plain-text search because people complained about the transition (the suggestions changed after a second for initial search)... Do you perceive the problem for all searches or only for the initialization?

If only initialization, we could add a loading indicator I guess,, if all searches then not sure, but in case it's because of using larger (more accurate) encodings/model/something, and we won't find easy solution, and if we are more confident in the API solution now, then it might be a good opportunity to try switching to API solution and compare the timings.

**Comment by ccstan99** [comment]
I haven't changed anything recently. There's been a recent release of tfjs (TensorFlow), so it's possible we should pin to a previous version in case something new is causing an issue. Otherwise, the model used shouldn't be larger or more accurate than before. The search space with the number of questions has grown but not signifcantly so. 

If it's only a lag in initialization, we might want to put the plain-text search back? Having an unexpected update seems minor compare to not being able to search at all. 

If it's a general lag, we could try with the API and compare. I was hoping to try testing that out later next week, if I have some time. The API does use a larger, supposedly more accurate model, but I don't expect it to be faster than running TF in-browser. Again, the main concern was all the traffic with live-updating as the user types, but certainly worth exploring.

**Comment by plexish** [comment]
Just initial search, but having had the tab open for a while still causes a long wait, is the initial load only happening once a person starts typing?

I think keyword to start with and accepting there will be one update is overall better, but not using keyword at all once the initial load is complete, might be best?

**Comment by tayler6000** [comment]
I noticed this as well, and it kinda gave me the impression Stampy didn't know anything.  I think a loading indicator would be a good addition to help prevent this conception to new comers.
