### ISSUE TITLE
Aesthetics: Unified color scheme + minimal cards + parralax + shadows

### ISSUE THREAD

**Issue by markovial** [StampyAI/stampy-ui#207]
Too many colors different colors is distracting and too loud. Having a simple unified color scheme would really help cleanup the aesthetic. In my mind this involves many hues of one (or two) 'thematic colors' and then the basic black white and gray. The thematic colors can be chosen from the current stampy logo. I extracted them from a color picker and am listing them here for convinience:

Stampy Red    : R : 217, G : 129, B : 107 | Hex : #D9816B
Stampy Yellow : R : 228, G : 212, B : 182 | Hex : #E4D4B6
Stampy Orange : R : 201, G : 144, B : 113 | Hex : #C99071
Stampy Blue-d : R : 190, G : 213, B : 236 | Hex : #BED5EC
Stampy Blue-l : R : 143, G : 157, B : 209 | Hex : #8F9DD1

As far as the cards go, I really liked the image that was posted on discord which was a clean pure black and white. Here it is for reference:

![image](https://user-images.githubusercontent.com/52564817/229863717-309f531c-5bd7-4496-bb65-e1f3ce9d0d14.png)

If we have links they can be one of the thematic colors chosen from above.

In order to indicate a contiguous answer the highlight colors could be used as a single line along the side of the answer card. here is an example picture of what I had in mind:

![image](https://user-images.githubusercontent.com/52564817/229864062-d5734491-91fe-40a1-9abe-5bd4d8941bc4.png)

The card would still be white with black text, just the left hand side highlight line could be one of the chosen theme colors. This makes it minimal and clean, but still succesfully indicates one contiguous answer.

I got a fair few of these suggestions from [this page](https://pointjupiter.com/ultimate-ux-ui-guide-card-design-web-sites-apps/). It has a whole bunch of suggestions around how to design cards. Another example suggestion is to have shadows offset to the bottom right as in the following example image or to not have them at all because shadows coming from all four directions looks unnatural:

![image](https://user-images.githubusercontent.com/52564817/229867004-8df1f431-e5f0-4507-bded-ff538b1fbc08.png)

Finally, to liven up the page a little without being too distracting, we can have a repeated texture parralax background in very light grey colors. The white foreground cards that contain the answers will then move independently of the parralax background and I think it would look nice. I didn't really find many example of this. [This website](https://www.fluttuo.com/) is kind of what I was thinking about where the background scrolls independently of the cards/information elements in the foreground, but minus the images and all that. Just a simple texture.

Here is one repeated texture background to indicate the kind of thing I am thinking about:

![image](https://user-images.githubusercontent.com/52564817/229864999-5c6810a1-d3fd-41b8-b441-87e5f9e28646.png)

But I have found these links to contain even more so that you can have your pick:

https://www.freepik.com/free-photos-vectors/repeated-texture  
https://www.freepik.com/free-photos-vectors/geometric-texture

I don't know how useful these suggestions are. Maybe a lot of this is just my aesthetic preferences for how I would like things to look, but it doesnt hurt communicating them.

**Comment by ccstan99** [comment]
Since we're communicating about aesthetics here, I'll park 2 mockups that domdurkovsky created a couple months back that was well-received on Discord. It doesn't fully specify all the features but give a nice cleaner look that's worth considering. 

If we're considering a facelifty redesign, some other refinements to explore, based on various feedback:
1. Tidy up format of search results and when adding new questions
2. Loading animation could be more subtle, maybe 3 gray dots fading in & out
3. Infinite scrolling should leave more margin/padding, maybe [load more] instead of automatically load
4. Have related questions fade in rather than slide in to minimize jarring motion

![domdurkovsky-stampy-dark](https://user-images.githubusercontent.com/38997995/234755949-89d5ddb2-89a0-411b-92f2-bd2a07727aa9.png)
![domdurkovsky-stampy-light](https://user-images.githubusercontent.com/38997995/234755954-732c98a3-2061-4a20-81b2-998f7b25b540.png)
