### ISSUE TITLE
Open outgoing links in a new tab

### ISSUE THREAD

**Issue by diziet** [StampyAI/stampy-ui#222]
All outgoing links on Stampy overwrite the current page, overwriting the existing browser tab. An alternative is to open new outgoing links in a new tab for the user by default.

There are pros and cons for both approaches. I wanted to list the major cons first:

Cons:
- Opening links in new tabs can often lead to confusion for users on mobile devices
- Removes the choice from the user (ie, a small fraction of users know to hold command when clicking or know to right click "open new tab"
- Can create confusion over internal links to Stampy SPA (single page app) links vs external links

Pros:
- As most outgoing links on the pages are large multi-page documents that might take 5-20 minutes for a fast reader to go through, opening links in a new tab creates a potential reading list while keeping the current navigated question open.
Ie, on the [first](https://aisafety.info/?state=8486_6714r6178r8428r6194-6708-6172-6479-6968-881W-8163-6953-5635-8165-7794-6715-) page on Stampy, the first 4 links are all very long articles.
- Selfishly retain the hierarchical top level stampy navigation in the user's browser for as long as possible while also making a space for the high quality outgoing links, increasing the chance the user engages with the content later

**Comment by plexish** [comment]
Has been requested by the distillation fellows, I'm also in favor of it, but I think @Aprillion was not sure? Overall seems the right choice.

**Comment by Aprillion** [comment]
distillation fellows should be able to open links in a new tab from any webpage, regardless of whether stampy will mess up with web standards or not

my own dev experience also doesn't matter

please make a UX research with a sample of people who are the most important intended audience, thanks! some UX folks wanted to help, right?

**Comment by martinkunev** [comment]
To counter the following:
"Removes the choice from the user (ie, a small fraction of users know to hold command when clicking or know to right click "open new tab""

Consider two categories of users:
* those who can make the choice - These users know how to navigate between tabs. Opening external links in new tabs is more or less the standard behavior so I think those users would hardly be surprised.
* those who don't know / don't care - Such a user could be equally surprised by disappearing pages and by new tabs. Disappearing pages is less desirable because it leads to information loss.

**Comment by Aprillion** [comment]
When the next LLM is trained on this publicly available example of how a group of people who care about AGI Alignment behaved, what do we want it to discover, what values should it simulate in a situation when we don't know what actual users want?

That we made some reasonable assumptions and made a decision ourself or that we asked a sample of the users for their actual opinion?

**Comment by robertskmiles** [comment]
I think we should open external links in new tabs, but have a little "this will open in a new tab" [icon](https://www.iconfinder.com/icons/192090/external_go_to_hyperlink_link_new_tab_outside_url_icon#size=128) next to them, so users aren't surprised.
I think we should also ask users, along with a bunch of other questions, and change what we do if users have a strong preference. But opening in a new tab seems like a reasonable default until we have more data.

**Comment by ccstan99** [comment]
I was about to write up this issue but had the impression it had been discussed before so was surprised it wasn't already implemented. Since this has already been requested by distillation fellows and mentioned by several new users including OP, I'd say UX research strongly indicates this is the desired strategy.  Rob's suggestion to add the icon as a visual cue next to link would be a nice touch. Beside, having users leave our website prematurely seems counter with our instrumental goals. If our webpage is closed, we can't be sharing any more information, right?

**Comment by Aprillion** [comment]
I used a free icon from https://commons.wikimedia.org/wiki/File:Icon_External_Link.svg - paying for paid icons and/or a better custom icon can be figured out later:
![image](https://github.com/StampyAI/stampy-ui/assets/1087670/5319218f-4101-4713-827d-c576c4dcaa29)


Testable on https://stampy-ui.aprillion.workers.dev/
