### ISSUE TITLE
Make wiki links to `allCanonicallyAnswered` questions open in UI

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#23]
In UI answer links to Google Docs with Status: `Live on-site` (or, equivalently, is in [this view](https://coda.io/d/AI-Safety-Info_dfau7sl2hmG/On-site-API_su5gl#_lu__Z)) should, when clicked, add the corresponding UI answer in an opened state directly below the current answer and scroll to it, rather than opening the Gdoc in another tab.

**Comment by ChrisRimmer** [comment]
Is this “load the plain text of the canonical answer from the wiki, and display that text inside rhe stampy UI”? If so can I check whether we have a way to retrieve the text of the answer programmatically? If we do this should be relatively straightforward, otherwise we might need to finagle a way to get answer text out of the wiki in a fairly clean and usable format.

**Comment by Aprillion** [comment]
FTR we have a list available from an API route on the CF Worker that is used internally by the UI client - https://ui.stampy.ai/questions/allCanonicallyAnswered - it is parsed from https://stampy.ai/w/api.php?action=ask&format=json&formatversion=2&query=[[Canonically%20answered%20questions]]|?CanonicalQuestions as the list of values from `fulltext` fields

**Comment by plexish** [comment]
> Not sure what is the purpose, where would you want to display it?

> Is this “load the plain text of the canonical answer from the wiki, and display that text inside rhe stampy UI”?

Yes, in particular do the same thing that happens when a user clicks on a search result and pop the new QA pair onto the screen, open, scrolled to the right place, and ready to read. I think Chris will need a pointer towards the bit of code used to add new QA pairs as well.

**Comment by Aprillion** [comment]
oh, I see what you mean now - if there is a link within an answer on the UI that points to another wiki question, we should render it as a link within UI and not as external link

@plexish do you have an example answer that contains a link to another question? (to use for testing)

@ChrisRimmer
* the code that displays a question on top of the UI when you click on search result is in https://github.com/StampyAI/stampy-ui/blob/42ad8c6ac623f625f2381d128ccd30425de9186b/app/routes/index.tsx#L98 `onSelect={selectQuestionByTitle}`
* parsing of wiki links happens in https://github.com/StampyAI/stampy-ui/blob/42ad8c6ac623f625f2381d128ccd30425de9186b/app/server-utils/stampy.ts#L59-L60 `html.replace(/href="\/wiki/g, 'href="https://stampy.ai/read')`

it should be possible to connect those 2 features, however it's not going to be trivial, we need to figure out how to trigger handlers defined by React Hooks when clicking on a link that is rendered by `dangerouslySetInnerHTML` in https://github.com/StampyAI/stampy-ui/blob/42ad8c6ac623f625f2381d128ccd30425de9186b/app/components/question.tsx#L81 .. probably some nasty hack will be needed ¯\\\_(ツ)_/¯ let me know if you are going to give it a try or if you want to pick some simpler feature first :D

**Comment by Aprillion** [comment]
FTR: parsed source from that question => https://ui.stampy.ai/questions/8157

**Comment by ChrisRimmer** [comment]
Just coming out of a week of avoiding doing any computering so should be able to take a look at this in the week.

**Comment by plexish** [comment]
@ChrisRimmer pinging to see if you've got capacity to take another shot at this :)

**Comment by ChrisRimmer** [comment]
Revisiting this. Aprillion was right in saying this requires some pretty ugly stuff - React needs to monitor for clicks on those Wiki links which would be fine if React was rendering the links directly, but because the links are just part of a big blob of HTML it's passing straight out to the browser it's, to put it briefly, non-trivial.

At a guess, doing this depends on building an actual answer renderer, something that can parse structured data from the backend and convert it into React components that it draws, which would let it watch for events on them as well as making it easier to do things like hiding long answers below a fold, as React would also be in charge of choosing how much of the answer to render.

Doing this is probably best kept until after the move off the Wiki, to save building such a parser twice, once for the Wiki and once for Google Docs, so I'm going to flag this as blocked and dependent upon the new core, whatever form that ends up taking.

**Comment by Aprillion** [comment]
Agree with waiting after we only display answers from Google Docs, so we can specify a list of all URL regex matchers that need special handling - either opening links directly in UI for other questions (to google docs / UI links / old wiki links too maybe?) or other special handling (what can replace current page, what should open on new tab...)

I imagine a global JS click handler (still React synthetic events, but on the root element, not for each link) that would check if a clicked link has some particular `href=...` pattern, so we wouldn't need special parser for answers, just a list of special URL patterns.

**Comment by plexish** [comment]
@Aprillion I updated the original spec to fit coda.

**Comment by Aprillion** [comment]
Now deployed on https://stampy-ui.aprillion.workers.dev/?state=0

**Comment by plexish** [comment]
🥳
