### ISSUE TITLE
Style search results

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#35]
https://www.figma.com/proto/gm06d1l5stMlnKxeElWBEc/Stampy-AI-Alignment-FAQ?node-id=116%3A415&scaling=min-zoom&page-id=116%3A414&starting-point-node-id=116%3A415

**Comment by ChrisRimmer** [comment]
I'm gonna be honest I got a bit excited now that I finally have a viable dev machine running and went ahead implementing this before noticing @ccstan99 is assigned. If you'd like to take a look at the pull request linked above where I had a go at this, it'd be appreciated.

**Comment by ccstan99** [comment]
No worries! I've completely forgotten about this so I'm more than thrilled that you're tackling it. Thanks! I'll take a look later today when I have some time.

**Comment by mruwnik** [comment]
A couple of additional things introduced by https://github.com/StampyAI/stampy-ui/pull/179

1.     Vertical height of dialogue shrinks after switching to thank you message, would be nice to also stay fixed.
2.     There probably should be a more explicit way (x in upper right and/or OK/Close button) to close the dialogue after the question has been requested/suggested. Not too critical since clicking outside closes it anyway.
