### ISSUE TITLE
/articles: articles linked under "Or jump to a related question" should open in same tab

### ISSUE THREAD

**Issue by ricewithabee** [StampyAI/stampy-ui#497]
![Image](https://github.com/StampyAI/stampy-ui/assets/98026499/4e5a7f31-26ad-4106-a3ad-9705fef95fc3)

The context ("Keep reading!") means the user clicks on them as the next step in their reading journey, as opposed to being a tangent (as the inline links are).

Remember to remove the arrows.

**Comment by mruwnik** [comment]
@melissasamworth ?

**Comment by melissasamworth** [comment]
Oh weird, I'm not sure how plurality (questions vs question) makes a difference there. I think this may be too small of a data point to make the change. Heh sorry I keep saying that. Just want more feedback and thinking of this round as MVP (not trying to be perfect because we still need more data to learn what perfect even is)
