### ISSUE TITLE
Tooltips background color

### ISSUE THREAD

**Issue by ccstan99** [StampyAI/stampy-ui#51]
All tooltips (icons at top, actions on questions, search question scores) should have the same background color #fed.

**Comment by ChrisRimmer** [comment]
Strictly speaking I wonder if we should avoid putting match scores in tooltips - at least if we're using the browser's built-in alt-text. I'm not super duper familiar with screen readers (you'd think after doing this almost a decade I would be, but alas!) but I'm fairly sure the title attributes we're using to generate these tooltips should just contain informative text for screen readers or other accessibility aids.

If we want to surface this info we can (are relevance scores useful? I want to say not very but I could easily be persuaded), but I think it would be most right to develop a little info tooltip component, which we can flag to the browser as explicitly not being an accessibility aid. Would also make styling them easier, as we'd be less constrained by the behaviour of the browser default tooltip renderer, which inherits styles from the parent element and as far as I know can't be targeted directly.

**Comment by Aprillion** [comment]
https://www.tpgi.com/using-the-html-title-attribute/ suggests that screen readers don't want to use `title` for accessibility due to lack of support ... I added score only for our debugging (if there are bad matches, to see if we can use some cutoff score to hide low-score matches or if score is unrelated to human evaluation).

This ticket is about replacing the built-in `title` tooltips with custom tooltips anyway, so we wouldn't be using `title` after we implement this, whether or not we keep scores.

**Comment by L-Sva** [comment]
I've implemented this change, using Tippy as the new tooltip library. I've changed the root.css file to use #fed for the tooltip background colour, which looks horrendous on my computer:
![image](https://user-images.githubusercontent.com/58653425/218275294-354761ac-f120-4cc8-b26d-cf4e175b9a6e.png)

**Comment by Aprillion** [comment]
@L-Sva there are 2 themes, `#fed` was intended for light theme (you can change the mode in browser dev tools to test it in light mode), feel free to use whatever doesn't look horrendous in dark theme inside the media query in CSS please
