### ISSUE TITLE
Chatbot: top 20 questions

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#605]
Context: After the user asks a question, we will return between 0 and 3 based on similarity to their original question. If the number is less than 3, we want to fill the rest at random with other questions. Preferably questions that users would click most. So we thought take the 20 current articles with questions you think users would click most in the chatbot, and show that to users at random. 

So we need those 20 questions. Feel free get input from various stakeholders about what those would be.

**Comment by melissasamworth** [comment]
@LeMurphant feel free to re-assign this

**Comment by LeMurphant** [comment]
I will discuss this with other fellows in the coming weeks

**Comment by LeMurphant** [comment]
Here are 19
[Do people seriously worry about existential risk from AI?](https://docs.google.com/document/d/1PTf4sitz2hMBWn6qFsB88NrEQEl-ItxkdtZGnvTcSxc/edit)
[Is AI safety about systems becoming malevolent or conscious?](https://docs.google.com/document/d/13cEDelaECCKZZsUNrI1lm7avM6ErMMoqYUhIpkVZ-RE/edit)
[When do experts think human-level AI will be created?](https://docs.google.com/document/d/1Oo3Ay25w6lOosi9E-idoRXAc1rQFWFPidmzxHj1usF4/edit)
[Why is AI alignment a hard problem?](https://docs.google.com/document/d/1mraQPWjVoTASnwLS1BbyBwvkIEuTy6_uwZ_yiPLyrco/edit)
[Why can’t we just “put the AI in a box” so that it can’t influence the outside world?](https://docs.google.com/document/d/1UWWcOAUxId09oB-y3_LkSQ9PCGJxAmj6DxTxpdUSSkY/edit)
[What are the differences between AGI, transformative AI, and superintelligence?](https://docs.google.com/document/d/1UvrweXuLJb3DkiwBh4WVQTqUYCVlC1WLgJoZywPSBek/edit)
[What are large language models?](https://docs.google.com/document/d/1ftH65iVEC6Q341Tv0I-BX0WZufu-lfnlGtdfVC3jYN4/edit)
[Why can't we just turn the AI off if it starts to misbehave?](https://docs.google.com/document/d/1wXSTtsD5RaleiR6S8NVcfpd8dxqGRDJL7Yy-WEn-ugg/edit)
[What is instrumental convergence?](https://docs.google.com/document/d/12cwXk6OcQMGAaxwsFKt0twpBlFlqHHoj2FV01PCyYVw/edit)
[What is Goodhart's law?](https://docs.google.com/document/d/1Fx4lB7XLRkZnusXLfqx9Ynh6pTcZGvIoQGNzDJZxnrM/edit)
[What is the orthogonality thesis?](https://docs.google.com/document/d/1_O_cQ4eKcPR-tng_vNhxf-TC8cT0NOfKs_AMph7j5M4/edit)
[How powerful would a superintelligence become?](https://docs.google.com/document/d/1933mx_fXY8VBvosoonXOiuHF_WCCbceqlS9X6pONoc8/edit)
[Will AI be able to think faster than humans?](https://docs.google.com/document/d/1qcJhXN9jSV-HzNYX8dEagvDhRuzCThaAOuhTfyV9HnA/edit)
[Isn't the real concern misuse?](https://docs.google.com/document/d/1YKA4i_3rfMMGrWLtvzNy9IplYgS4Ialdc6f-Rfu-CBg/edit)
[Are AIs conscious?](https://docs.google.com/document/d/1MVwxrGRY6ALgneDvsCaBmHnM2TPH1iOhwZA8g8Qxw44/edit)
[What are the differences between a singularity, an intelligence explosion, and a hard takeoff?](https://docs.google.com/document/d/1WJraCVimbHI8VjZaZqT-eNW2kb_Yjbc5Jbl0TjMXnV0/edit)
[What is an intelligence explosion?](https://docs.google.com/document/d/1o_CnFOMGmL1hniT3dasrh6id67buwOwjU6R8zHrhMbk/edit)
[How might AGI kill people?](https://docs.google.com/document/d/1MbvOfA8E_jRNtA6rDSBmUaiB6j_exlUIoauzY85Ofek/edit)
[What is a "warning shot"?](https://docs.google.com/document/d/1-lW3UKdEKNsqjMpFWmLZjJKDiVfgQmOogi-RbJ1imXU/edit)
