### ISSUE TITLE
Clicking on search result sometimes does nothing

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#741]
Tested on live site, seems to only happen with https://aisafety.info/questions/89LL/
[not_loading.zip](https://github.com/user-attachments/files/15958129/not_loading.zip)

**Comment by Aprillion** [comment]
Huh, this one is tricky, but I think I got repro steps:

* search for `exi` (or something with top search result being a long title)
* start clicking and hold on the 3rd result
  * the search bar will shrink on mousedown => mouse position will be on the 2nd result instead of 3rd
  * click event won't happen
* in the shrinked search results, click on the 3rd result again
  * works fine
 
=> if I can fix the shrinking on mousedown, that should also fix this issue 🤞
