### ISSUE TITLE
Pulling LW tags sometimes pulls an old version

### ISSUE THREAD

**Issue by LeMurphant** [StampyAI/stampy-ui#744]
https://aisafety.info/questions/8C7W/
https://docs.google.com/document/d/1CoeLLw-Rz8CT4FLO5KkngSDrR8-px98WBrC1f7ykd1w/edit
https://www.lesswrong.com/tag/optimization/history
![LW_tag_history](https://github.com/StampyAI/stampy-ui/assets/16197732/195780cc-7c6d-433f-8a7e-6ce68dc332a4)
![Old LW tag on site](https://github.com/StampyAI/stampy-ui/assets/16197732/ec625463-709f-4eb7-b4a4-d01e743a9079)

Note that it pulls from something that is close to what is in the history, but there does not seem to be an exact match. I have not tested if it does it all the time or only this once.

I am also told that we currently cannot pull tags from the Alignment Forum, this would be a nice fix while we are at it.

**Comment by LeMurphant** [comment]
Now it just pulls nothing
![link to tag](https://github.com/user-attachments/assets/e92d9691-73dc-4cc4-b015-746c2f4bf9f7)

**Comment by mruwnik** [comment]
There are a couple of things going on here.

* The LW system has changed over the years, and some tags are using an older version for storing data - I updated the code to use a fallback to fetching the html rather than markdown for these
* Alignment forum tags should now be supported
* The Coda contents only get updated when a gdoc changes. This means that when an editor supplies a tag link to use as content, then it will be fetched once and left alone until that gdoc file changes again. This is to say that it doesn't track LW tag updates. It would be possible to implement that, but it would be a lot of work so I don't want to right now... That being said, if you think it valuable it can certainly be done

**Comment by LeMurphant** [comment]
This makes sense, thanks for the explanation. This being said, I see that you changed the tag to point to alignmentforum.org, which afaik does not work, which is why we were using LW ones. Was there a reason for that?

**Comment by LeMurphant** [comment]
Also I think that the workaround for re-parsing that make a lot of sense, and making it automatic is low priority.

**Comment by mruwnik** [comment]
Are you sure about it not working?
![image](https://github.com/user-attachments/assets/ff95d904-8121-491f-a8a2-029926f4c1cd)
