### ISSUE TITLE
Set up analytics

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#81]
Set up an analytics platform so we can learn about which questions get clicks and start A/B testing.

Desired features:
1. Exclude EU for GDPR reasons (we don't want to have cookie notices)
2. Ability to watch recorded user sessions (does not need to be a huge number)
3. Collect statistics on how many times any given question is displayed and how many times it is clicked and opened (and the ratio between them) - also used for initial questions
4. Collect statistics on the last question a user clicks before leaving
5. Ability to run A/B tests on general site features (e.g. intro line)
6. Statistics on average time on site, answers opened count, links clicked, etc
7. Logging each search in the search bar (but cutting the half-typed ones when immediately followed by an extended string)
8. Stats on what people clicked before clicking to a specific question (e.g. "I'm convinced, how can I help?")

Perhaps one of these would work
https://livesession.io/ 
https://logrocket.com/
https://www.smartlook.com/
https://mouseflow.com/
https://www.inspectlet.com/
https://watchthem.live/
https://www.hotjar.com/

Or something else.

**Comment by jmccuen** [comment]
Looked in to this a but, and it seems like point #1 might not really be a thing? (If someone knows of a way, please correct me). I can't find a simple "turn off tracking for the EU" option for any of the analytics platforms with session recordings.

Based (limited) understanding / reading of GDPR, this is because all the session recording tools use cookies (since that's literally what tracks the session) and under GDPR cookie IDs are considered personal data (this is the bit I'm most unclear about)

It also doesn't seem to work to just enable tracking by region/ geo (via ip range etc), because a) VPNs and b) GDPR applies to EU citizens even when they are abroad.

Best I can tell, the only way to avoid the cookie popup / privacy policy is to not use cookies, eg using server-side tracking via api calls that do not include personal data, but this necessarily prevents us from (at least) the session replay requirement.

**Comment by plexish** [comment]
Seems plausible.

Discussed via DM and settled on server-side API, plus maybe later adding a thing to collect a tiny number of sessions and showing cookie notices to just those people.
