### ISSUE TITLE
QA and minor fixes

### ISSUE THREAD

**Issue by melissasamworth** [StampyAI/stampy-ui#817]
- Make sure all the copy uses official American English spelling (e.g. "organization" not "organization")
- Go through the rest of the website and make sure nothing is broken (including mobile)
- In the cases where we actually want AI safety to be capitalized (e.g. AI Safety Quest) make sure it's capitalized (site wide, actually, if you could)
- Wait on going through the rest of the How can I help section because I'll give it one last pass first
- comment out any sections that we don't have testimonials from people for
- if we only have one, use the design for the careers page which features Bryce (and only has one)
- Also, I used single quotes in some places, but I'm thinking just change them all to double (or whatever we do elsewhere)

**Comment by bryceerobertson** [comment]
@melissasamworth .info uses American English 
![Uploading Screenshot 2024-10-28 at 15.10.14.png…]()

**Comment by bryceerobertson** [comment]
To do list:
- [ ] Make sure all the copy uses official American English spelling (e.g. "organization" not "organization")
- [ ] Go through the rest of the website and make sure nothing is broken (including mobile)
- [ ] In the cases where we actually want AI safety to be capitalized (e.g. AI Safety Quest) make sure it's capitalized (site wide, actually, if you could)
- [ ] Wait on going through the rest of the How can I help section because I'll give it one last pass first
- [ ] comment out any sections that we don't have testimonials from people for
- [ ] if we only have one, use the design for the careers page which features Bryce (and only has one)
- [ ] Also, I used single quotes in some places, but I'm thinking just change them all to double (or whatever we do elsewhere)

**Comment by melissasamworth** [comment]
Actually a couple more things:

Double check and make sure all the links go to the right place
Double check to make sure the text matches the Figma. There are many places I'm seeing where it doesn't match.

**Comment by bryceerobertson** [comment]
@melissasamworth Regarding text in Figma – remember I've been making small copy changes where I think they should be made, so that could be some of them. But yeah I'll check everything.

**Comment by melissasamworth** [comment]
> @melissasamworth Regarding text in Figma – remember I've been making small copy changes where I think they should be made, so that could be some of them. But yeah I'll check everything.

That's fine. What kind of changes are you making though?

**Comment by bryceerobertson** [comment]
Generally very minor stuff e.g. "Map of EA groups" instead of "EA groups map"
