### ISSUE TITLE
Paper search

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#90]
Using https://ai-safety-papers.quantifieduncertainty.org/table as the backend database. Include results in the Semantic Search results, with an icon of a paper/scroll, and either have that open in new tab or in a normal QA box with answer set to the last field ("Shah blurb") with a prominent link to "read full paper".

Thoughts on which of these would be best?

**Comment by plexish** [comment]
Might be worth having in mind when expanding to this extra content type for search that we might include [videos](https://www.lesswrong.com/posts/tas3QZfKm4bdnAWsZ/ai-alignment-youtube-playlists) or other types in future.

**Comment by ccstan99** [comment]
@plexish, I had a prototype paper search at https://nlp.stampy.ai/literature but never fully tested or integrated it. I'm thinking doing this within the chatbot feels like a more natural solution. Would you be ok with me closing this issue here and addressing it as https://github.com/StampyAI/stampy-chat/issues/36?

**Comment by plexish** [comment]
@ccstan99 Yes, that seems reasonable.
