### ISSUE TITLE
Some websites parse out the trailing underscore

### ISSUE THREAD

**Issue by plexish** [StampyAI/stampy-ui#91]
e.g. If you post a raw link to an answer to github like
https://ui.stampy.ai/?state=8157_

The _ gets stripped, so the link does not work. Can we detect when the last pageid is missing a control character and re-add it? Or just assume open if the control character is missing?

**Comment by Aprillion** [comment]
hm, sounds like bug (or feature because of "reasons") in github sicne `_` doesn't need to be escaped in URLs,, but we can use a letter e.g. `8157v` to make it more compatible

we should also make the open status as default when the last character is missing (manual copy&paste error can happen even if we change the character), instead of empy page

**Comment by plexish** [comment]
There are already links spreading around so not sure if dropping support for _ is a good idea? And even if we supported both, I quite like _ and - when reading the URLs. v and > would be okay, but are less visually distinct.

Would having blank control characters interpreted as _ not work?

**Comment by Aprillion** [comment]
I see, we want to keep _ but if some place (like github comments) render the link without the trailing _ we want to recover from the shortened link, assuming 1 missing character was _.

Looks like _ works fine in the middle, so it's just the 1 trailing character: https://ui.stampy.ai/?state=6714_6184_
