### ISSUE TITLE
Color for already open questions in search results

### ISSUE THREAD

**Issue by Aprillion** [StampyAI/stampy-ui#99]
Current color for already open question in search results is defined as:
```css
.result-item.already-open {
  color: var(--colorLinkVisited);
```
![image](https://user-images.githubusercontent.com/1087670/186611891-7bee90e6-37ed-42be-b57c-cdd3d01384ae.png)

However, the clickable search results are white and this color makes it look like the disabled item is a link.

We should find a a new color (at least for the dark scheme).

**Comment by jmccuen** [comment]
What about something purple like #c38?

**Comment by Aprillion** [comment]
@jmccuen hmm, looks interesting, but perhaps something that draws *less* attention to the disabled items 🤔 I was thinking one of the gray colors..

looks like I forgot to tag @ccstan99 - do you prefer blue, purple, gray, or some different solution to the disabled search results?

**Comment by ccstan99** [comment]
Ahh, I see. I originally picked the visited link color since it was already open/visited. But since it's disabled and not an actual link, that could be confusing. So #999 a medium gray will work for both dark & light scheme and also indicate its "disability".
<img width="1004" alt="Screen Shot 2022-09-07 at 8 27 22 PM" src="https://user-images.githubusercontent.com/38997995/189029473-4ab6a901-c66e-4192-aa58-f910119506be.png">
<img width="996" alt="Screen Shot 2022-09-07 at 8 27 34 PM" src="https://user-images.githubusercontent.com/38997995/189029477-bf969bc7-7543-4d2c-a906-c0f3b741ae90.png">
